In [14]:
import pandas as pd
import numpy as np
from sklearn import linear_model

 Summary: This is a hiring statics for a firm such as experenice of candidate based on written test score and personal interview score. HR will decide the salary of the candidate. Given this data you need to build a machine learning model for. thee HR Department that will help them decide salaries for future candidates. Uisng this predict salariees for the following candidates 

2yrs experiences, 9 test score, 6 interview score
12yrs experiences, 10 test score, 10 interview score
9yrs experiences, 10 test score, 9 interview score
24yrs experiences, 4 test score, 3 interview score

In [15]:
df=pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [16]:
df.rename(columns={"test_score(out of 10)":"test_score", 
                   "interview_score(out of 10)":"interview_score",
                  "salary($)":"salary"}, inplace = True)
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [17]:
#To replace the missing value in column "test_score" by finding the mean of the column
df["test_score"].mean()


7.857142857142857

In [18]:
#To replace the missing value with the mean of the column
df.test_score = df.test_score.fillna(df["test_score"].mean())



In [19]:
df

experience  test_score  interview_score  salary
0        NaN    8.000000                9   50000
1        NaN    8.000000                6   45000
2       five    6.000000                7   60000
3        two   10.000000               10   65000
4      seven    9.000000                6   70000
5      three    7.000000               10   62000
6        ten    7.857143                7   72000
7     eleven    7.000000                8   80000

In [22]:
#Fill the missing value in column "experience" with "one"
df.experience=df.experience.fillna("one")
df

experience  test_score  interview_score  salary
0        one    8.000000                9   50000
1        one    8.000000                6   45000
2       five    6.000000                7   60000
3        two   10.000000               10   65000
4      seven    9.000000                6   70000
5      three    7.000000               10   62000
6        ten    7.857143                7   72000
7     eleven    7.000000                8   80000

In [ ]:
#df['experience'] = df['experience'].astype("int32").dtypes
#df['experience'] = pd.to_numeric(df['experience'])
#import math


In [23]:
#Replacing the numbers in text in "experience" column to integers
df['experience'] = df['experience'].replace(['one','five','two','seven','three','ten','eleven'], [1,5,2,7,3,10,11])
df['experience']
df

experience  test_score  interview_score  salary
0           1    8.000000                9   50000
1           1    8.000000                6   45000
2           5    6.000000                7   60000
3           2   10.000000               10   65000
4           7    9.000000                6   70000
5           3    7.000000               10   62000
6          10    7.857143                7   72000
7          11    7.000000                8   80000

## Linear Regression to predict salary

Dependent:  Salary
Independent/ features variable: experience, test_score, interview_score

#Formula: Salary =M1*experience + M2*test_score + M3*interview_score + b

y=m1x1 + m2x2 + m3x3 + b

In [25]:
#To call in the linear regression function
reg=linear_model.LinearRegression()
reg

LinearRegression()

In [26]:
#drop the dependent variable ("salary")
hir = reg.fit(df.drop("salary", axis = "columns"), df.salary)


In [27]:
#1. To predict salary for experience=2, test_score=9, interview_score=6
reg.predict([[2,9,6]])

C:\Users\worten\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([51450.95746952])

In [28]:
#2.To predict salary for experience=12, test_score=10, interview_score=10 
reg.predict([[12,10,10]])

C:\Users\worten\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93813.20803007])

In [29]:
#3. To predict salary for experience=9, test_score=10, interview_score=9
reg.predict([[9,10,9]])

C:\Users\worten\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([82189.44356842])

In [30]:
#4.To predict salary for experience=24, test_score=4, interview_score=3

reg.predict([[24,4,3]])

C:\Users\worten\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([101255.40820371])

#To confirm the statistical model using math formula


In [34]:

reg.intercept_

12807.283160594336

In [35]:
reg.coef_

array([3048.17655662, 1963.54582722, 2479.23479178])

In [36]:
#To get question 1 using mathematical formula (2,9,6)
y_1=(3048.17655662*2) + (1963.54582722*9) + (2479.23479178*6) + 12807.283160594336
y_1

51450.95746949434