# Machine Learning With Python: Linear Regression Multiple Variables

In [ ]:
Sample problem of predicting home price in monroe, new jersey (USA)

In [ ]:
Given these home prices find out price of a home that has,

3000 sqr ft area, 3 bedrooms, 40 year old

2500 sqr ft area, 4 bedrooms, 5 year old

In [16]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
df.bedrooms.median()

4.0

In [10]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
reg = linear_model.LinearRegression()
reg

LinearRegression()

In [38]:
x_train = reg.fit(df.drop("price", axis = "columns"), df.price)
x_train

LinearRegression()

In [37]:
reg.score(df.drop("price", axis = "columns"), df.price)

0.9550196399325818

In [20]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [21]:
reg.intercept_

221323.00186540408

In [23]:
#3000 sqr ft area, 3 bedrooms, 40 year old
reg.predict([[3000,3,40]])

/Users/apple/Desktop/Anaconda/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [26]:
#Formular: Price = M1*area +M2*bedroom+ M3*age + b
112.06244194*3000 + 23388.88007794* 3 + -3231.71790863*40 + 221323.00186540408

498408.2515740241

In [44]:
#2500 sqr ft area, 4 bedrooms, 5 year old
reg.predict([[2500,4,5]])

/Users/apple/Desktop/Anaconda/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [47]:
reg.predict([[3500,3,5]])

/Users/apple/Desktop/Anaconda/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([667549.59935353])