1) Write a NumPy program to get help on the add function.

2) Write a NumPy program to create an array with values ranging from 12 to 38.

3) Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

4) Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

5) Write a NumPy program to append values to the end of an array.

6) Write a NumPy program to generate five random numbers from the normal
distribution.

7) Write a NumPy program to get the n largest values of an array.

**Q1:Write a NumPy program to get help on the add function**

In [1]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**Q2:Write a NumPy program to create an array with values ranging from 12 to 38.**


In [2]:
val = np.arange(12, 38)
print(val)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


**Q3: Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.**

In [4]:
np.arange(2,11).reshape((3,3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

**Q4: Write a NumPy program to create a 2d array with 1 on the border and 0 inside**

In [5]:
arr = np.ones((3,3))
print("Original array:")
print(arr)
print("1 on the border and 0 inside in the array")
arr[1:-1,1:-1] = 0
print(arr)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


**Q5: Write a NumPy program to append values to the end of an array.**

In [7]:
arr1=np.array([[1, 2, 3], [4, 5, 6]])  
arr2=np.array([[7, 8, 9], [10, 11, 12]])  
arr3=np.append(arr1, arr2)  
print(arr3) 

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Q6: Write a NumPy program to generate five random numbers from the normal
distribution**

In [8]:
np.random.rand(5)

array([0.98243538, 0.11515455, 0.83685419, 0.42743972, 0.99922251])

**Q7: Write a NumPy program to get the n largest values of an array**

In [9]:
scores = np.array([100,67,92,87,66,89,76,22])
scores.max()

100